Store records in their own repository contexts
kbss-cvut/record-manager pull request #6
Opened 2023-11-02 11:08 UTC by ledsoft

Implements kbss-cvut/23ava-distribution#10

2023-11-13 08:55 UTC, ledsoft commented
Since this PR has not been merged, yet, the new changes implementing kbss-cvut/23ava-distribution#11 have been automatically added to it.

2023-11-13 08:59 UTC, ledsoft commented
Also I noticed that there is a [draft](https://github.com/orgs/kbss-cvut/projects/10/views/1#) of a ticket for migrating Record Manager from RDF4J to GraphDB. The Docker Compose setup I created uses GraphDB, so maybe that ticket can be closed as well.

2023-11-19 10:43 UTC, blcham requested changes
LGTM, just minor suggestions.

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +  record-manager:
```suggestion
  record-manager-server:
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +    image: record-manager
```suggestion
    image: record-manager-server
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +  record-manager-ui:
```suggestion
  record-manager:
```

2023-11-19 10:43 UTC, blcham commented on db-server/repo-config/config-record-manager.ttl
> +<#termit> a rep:Repository;
```suggestion
<#record-manager-app> a rep:Repository;
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +    container_name: record-manager
```suggestion
    container_name: record-manager-server
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +      REPOSITORYURL: "http://db-server:7200/repositories/record-manager"
```suggestion
      REPOSITORYURL: "http://db-server:7200/repositories/record-manager-app"
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +      - record-manager
```suggestion
      - record-manager-server
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +      API_URL: "http://localhost:8080/record-manager"
```suggestion
      API_URL: "http://localhost:8080/record-manager-server"
```

2023-11-19 10:43 UTC, blcham commented on docker-compose.yml
> +      API_URL: "http://localhost:8080/record-manager"
Maybe this requires also "context-path" setting in  service "record-manager-server".

2023-11-19 14:34 UTC, merged